In [9]:
import cv2
import numpy as np

cap = cv2.VideoCapture('videos/demo1.mp4')

ret, first_frame = cap.read()
print(first_frame, type(first_frame))
print(first_frame.shape)

prev_gray = cv2.cvtColor(first_frame, cv2.COLOR_BGR2GRAY)

mask = np.zeros(first_frame)


mask[..., 1] = 255

while(cap.isOpened()):
    ret, frame = cap.read()
    cv2.imshow('input', frame)
    
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    flow = cv2.calcOpticalFlowFarneback(prev_gray,
                                       gray,
                                       None,
                                       0.5,
                                       3,
                                       15,
                                       3, 
                                       5,
                                       1.2,
                                       0)
    magn, angle = cv2.cartToPolar(flow[..., 0],
                                 flow[..., 1])
    
    # Set image hue depending on optical flow direction
    mask[.../ 0] = angle*180/np.pi/2
    
    # Normalize magnitude
    mask[..., 2] = cv2.normalize(magn,
                                None,
                                0,
                                255,
                                cv2.NORM_MINMAX)
    
    # Convert hsv to rgb
    rgb = cv2.Color(mask, cv2.COLOR_HSV2RGB)
    
    cv2.imshow('Dense Optical Flow', rgb)
    prev_gray = gray
    
    if cv2.waitKey(0) & 0xFF == ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()
    

[[[ 97 119 134]
  [ 93 115 130]
  [ 92 114 129]
  ...
  [ 45  48  46]
  [ 40  43  41]
  [ 41  44  42]]

 [[100 122 137]
  [ 98 120 135]
  [ 96 118 133]
  ...
  [ 44  47  45]
  [ 42  45  43]
  [ 47  50  48]]

 [[ 99 124 138]
  [ 96 121 135]
  [ 94 119 133]
  ...
  [ 41  44  42]
  [ 42  45  43]
  [ 47  50  48]]

 ...

 [[100 117 115]
  [100 117 115]
  [102 119 117]
  ...
  [ 53  60  53]
  [ 62  69  62]
  [ 64  71  64]]

 [[ 96 113 111]
  [ 96 113 111]
  [104 121 119]
  ...
  [ 49  56  49]
  [ 59  66  59]
  [ 64  71  64]]

 [[ 96 113 111]
  [ 90 107 105]
  [ 95 112 110]
  ...
  [ 53  60  53]
  [ 61  68  61]
  [ 69  76  69]]] <class 'numpy.ndarray'>
(1920, 1080, 3)


ValueError: maximum supported dimension for an ndarray is 32, found 1920